'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { PageFrame } from '../../components/site-shell';

export default function Contact(){
  const [sent,setSent]=useState(false); const [error,setError]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError('');const f=new FormData(e.currentTarget);const res=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f.entries()))});if(res.ok)setSent(true);else{const data=await res.json().catch(()=>({}));setError(data.error||'Something went wrong. Please try again.')}setLoading(false)}
  return <PageFrame><main className="section-light contact-page"><section className="container contact-head"><div><div className="eyebrow">Start a conversation</div><h1>Tell us what the operation needs.</h1><p>There are two ways to work with us. Choose a standard solution if it matches your need. If your problem is specific, bring us the workflow and we'll discuss a personal solution.</p></div><div className="contact-choice"><Link href="/solutions"><strong>01 / STANDARD</strong><span>I found my solution →</span></Link><a href="#personal"><strong>02 / PERSONAL</strong><span>I have a different problem →</span></a></div></section><section id="personal" className="container contact-form-wrap">{sent?<div className="success-box"><div className="eyebrow">Request received</div><h2>Good. We have the problem context.</h2><p>We'll use the information you shared to prepare the next technical conversation.</p></div>:<form onSubmit={submit} className="contact-form"><div className="form-intro"><div className="eyebrow">Personal solution</div><h2>Bring the problem.<br/>We'll map the system.</h2></div><div className="form-fields"><input name="name" required placeholder="Name"/><input name="company" required placeholder="Company"/><input name="role" required placeholder="Role"/><input name="email" required type="email" placeholder="Work email"/><input name="plantLocation" placeholder="Plant / location"/><textarea name="challenge" required placeholder="What is the operational problem?" rows={6}/><textarea name="currentTools" placeholder="What do you use today? (Excel, ERP, GMAO, email, etc.)" rows={4}/>{error&&<p className="signal">{error}</p>}<button disabled={loading} className="button button-dark" type="submit">{loading?'SENDING…':'SEND PROBLEM BRIEF ↗'}</button></div></form>}</section></main></PageFrame>
}
